spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ssm?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT"
    username: "root"
    password: "123456"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  security:
    user:
      name: admin
      password: 1
#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
logging:
  config: classpath:templates/log4j.xml

#    static-path-pattern: /static/**

#配置mapper
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
